### ISSUE TITLE
Could not find a part of path 'F:\Modulous\mod_store'.

### ISSUE THREAD

**Issue by wholton** [ModulousSmash/ModulousMM#1]
Running the program from my secondary HDD (path: "E:\Programs\PROJECT M\Modulous\ModulousMM.exe"). Windows 7 64-bit. Let me know if you need any other information. Here's the detailed output:

"See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Modulous\mod_store'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at ModulousMM.MainForm.reload_mods()
   at ModulousMM.MainForm.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18444 built by: FX451RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

ModulousMM
    Assembly Version: 0.9.5654.18633
    Win32 Version: 0.9.5654.18633
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/ModulousMM.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

CreativityKitchen.CreativityWin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/CreativityKitchen.CreativityWin.DLL

XDMessaging
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/XDMessaging.DLL

ModulousLib
    Assembly Version: 0.9.5654.18632
    Win32 Version: 0.9.5654.18632
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/ModulousLib.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

NLua
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/NLua.DLL

KeraLua
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2.0
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/KeraLua.DLL

Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/Newtonsoft.Json.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

XDMessaging.Transport.Amazon
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/XDMessaging.Transport.Amazon.DLL

XDMessaging.Transport.IOStream
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/XDMessaging.Transport.IOStream.DLL

XDMessaging.Transport.WindowsMessaging
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/XDMessaging.Transport.WindowsMessaging.DLL

AWSSDK
    Assembly Version: 1.5.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///E:/Programs/PROJECT%20M/Modulous/XDMessaging.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box."

**Comment by EIREXE** [comment]
Hello there, I assume your SD Card path is set to F:\ right?

**Comment by wholton** [comment]
Yes, that's correct.

**Comment by EIREXE** [comment]
Okay, try redownloading modulous.net/static/update.zip because I fucked up the updater, this build should work.

**Comment by EIREXE** [comment]
Nevermind, I found the origin of the bug.

**Comment by EIREXE** [comment]
Alright, the bug should be fixed now, can you download http://modulous.net/static/update.zip and confirm that it has been fixed?

**Comment by wholton** [comment]
That seems to have done it. I get "InvalidArgument=Value of '0' is not valid for 'index'." when clicking "Install mod from website." Not knowing the exact function of this button, my guess is that it should give me a list of available mods from the site.

**Comment by EIREXE** [comment]
Actually, it shouldn't work if you haven't selected a list, since the list gets filled up on launch, but there are no mods that have support for the manager yet, so it breaks, i'll fix it on the next big release, since it's a minor bug.
