### ISSUE TITLE
SD card and switching the path

### ISSUE THREAD

**Issue by DismalAmoeba** [ModulousSmash/ModulousMM#2]
An SD card will keep the set mod root path as is, appearing to not do anything after you try to switch the path. Removing the SD card and reloading Settings will switch the path to the new location.

**Comment by EIREXE** [comment]
So if you change it in the settings it does not change?

In that case it is a visual bug, and the setting has be en changed, it just doesn't show up in the settings window until you close it and open it again.

Should be fixed on next release.

**Comment by EIREXE** [comment]
Fixed in 990e68b5c39633fd60154b16389ccdc8bd8db3ae
