### ISSUE TITLE
Load Debugging Console and Install Mod From ZIP File does nothing...?

### ISSUE THREAD

**Issue by DismalAmoeba** [ModulousSmash/ModulousMM#5]
Is it supposed to do that? No errors or anything. The mod doesn't get added either. If you want, I can upload the mod I'm trying to make compatible, though it isn't mine. (I plan to get permissions when I upload it, just wanted to practice)

**Comment by EIREXE** [comment]
This will be fixed in the next patch, it's coming out in a few mins, when you open the manager you will be prompted to update.

This has been fixed in c0c14537fb99a222dc62e155d723fbbeef16245f

**Comment by DismalAmoeba** [comment]
Ah, sweet. Hopefully the mod will start working.
