### ISSUE TITLE
Updated after prompt, fails to update after another prompt

### ISSUE THREAD

**Issue by DismalAmoeba** [ModulousSmash/ModulousMM#6]
*************\* Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\DismalAmoeba\Desktop\Modulous Mod Manager (1)\updater.dat'.
File name: 'C:\Users\DismalAmoeba\Desktop\Modulous Mod Manager (1)\updater.dat'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at ModulousMM.MainForm.Form1_Load(Object sender, EventArgs e) in c:\Users\ALEX\Documents\Visual Studio 2013\Projects\ModulousLib\ModulousMM\MainForm.cs:line 98
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

ModulousMM
    Assembly Version: 0.9.5655.2472
    Win32 Version: 0.9.5655.2472
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/ModulousMM.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

XDMessaging
    Assembly Version: 4.0.9.0
    Win32 Version: 4.0.9
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/XDMessaging.DLL

ModulousLib
    Assembly Version: 0.9.5655.2242
    Win32 Version: 0.9.5655.2242
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/ModulousLib.DLL

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

NLua
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/NLua.DLL

KeraLua
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2.0
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/KeraLua.DLL

Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.8.18111
##     CodeBase: file:///C:/Users/DismalAmoeba/Desktop/Modulous%20Mod%20Manager%20(1)/Newtonsoft.Json.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.5.27.0 built by: FX453PREVIEWREL
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by EIREXE** [comment]
Is there an updater.exe in the folder? if so rename it to updater.dat.

Or try starting with a fresh folder.

**Comment by DismalAmoeba** [comment]
It works.
